apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-generator-ex
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{name}}-application'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/muhsufyan/deploy-Q-A-model.git
        targetRevision: main
        path: deploy
      destination:
        server: '{{server}}'
        namespace: cluster-generator
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
