name: Build Docker Image Pytroch CPU
# on:
#   push:
#     branches:
#       - main
on: workflow_dispatch

jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: login to docker hub
          id: docker-hub
          env:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_PASSWORD}}
          run: |
            docker login -u $username -p $password 
        - name: build the docker image
          id: build-docker-image
          run: |
            ls -la 
            docker build . -f ./build-cpu-version/Dockerfile -t tetewpoj/fastapi-model-qna
        - name: push the docker image
          id: push-docker-image
          run: docker push tetewpoj/fastapi-model-qna
            # Run docker image
        - name: Run the build process with Docker
          uses: addnab/docker-run-action@v3
          with:
            image: tetewpoj/fastapi-model-qna
